name = "iridescent-logo"
pages_build_output_dir = "./public"
compatibility_date = "2026-10-01"

[[durable_objects.bindings]]
name = "PRESENCE"
class_name = "Presence"
script_name = "iridescent-presence"
